### ISSUE TITLE
关于本博客的说明 | Attack博客

### ISSUE THREAD

**Issue by attack204** [attack204/attack204.github.io#3]
http://attack204.com/2018/04/30/%E5%85%B3%E4%BA%8E%E6%9C%AC%E5%8D%9A%E5%AE%A2%E7%9A%84%E8%AF%B4%E6%98%8E/ 

 好久没有更新过这个博客了，因为本人实在太懒了QWQ。。不过今天实在是看不下去了，友言4.30就倒闭了，所以换了一个新的评论系统——valine，不得不说，这个评论系统是真的好用然后又优化了很多细节，比如右下角那个看板娘，不过我不知道怎么改样式啊QWQ…不管怎么改都是那一个小人，大小也没法改QWQ….至于博客内容的话，有空就更新吧，主要还是用博客园

**Comment by attack204** [comment]
Test

**Comment by rbzno1** [comment]
外校萌新前来膜拜Orz

**Comment by hydingsy** [comment]
Orz attack

**Comment by Mout-sea** [comment]
Orz attack
